services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: painting_crew_app
    volumes:
      - .:/app
      - deps:/app/deps
      - build:/app/_build
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
    command: sh -c "mix setup && mix phx.server"

volumes:
  deps:
  build:
